Repository thoth-station/workflow-helpers, pull requests merged in 2020-10, with the labels that each got.

#122 Feature/is analyzable message
  Pipfile
  Pipfile.lock
  download_py_package.py
Labels: approved, size/L

#124 Automatic update of dependency thoth-storages from 0.25.13 to 0.25.14
  Pipfile.lock
Labels: approved, bot, size/M

#126 Automatic update of dependency thoth-messaging from 0.7.8 to 0.7.10
  Pipfile.lock
Labels: approved, bot, size/M

#128 Correct import and add defaults
  download_py_package.py
Labels: approved, size/S

#130 Release of version 0.1.14
  CHANGELOG.md
  thoth/workflow_helpers/__init__.py
Labels: approved, bot, size/S

#131 Do not fail on known errors
  download_py_package.py
Labels: approved, size/S

#132 Assign datatype in message
  download_py_package.py
Labels: approved, size/M

#134 Release of version 0.1.15
  CHANGELOG.md
  thoth/workflow_helpers/__init__.py
Labels: approved, bot, size/XS

#136 Qebhwt workflow now saves the adviser message
  .env.template
  .gitignore
  qeb_thamos_advise.py
Labels: approved, size/M

#138 Automatic update of dependency thoth-storages from 0.25.14 to 0.25.15
  Pipfile.lock
Labels: approved, bot, size/M

#139 Automatic update of dependency thoth-messaging from 0.7.10 to 0.7.11
  Pipfile.lock
Labels: approved, bot, size/M

#142 Release of version 0.1.16
  CHANGELOG.md
  thoth/workflow_helpers/__init__.py
Labels: approved, bot, size/S

#143 Fix sourcetpye
  qeb_thamos_advise.py
Labels: approved, size/XS

#145 Automatic update of dependency thoth-common from 0.20.0 to 0.20.1
  Pipfile.lock
Labels: approved, bot, size/S

#147 Release of version 0.1.17
  CHANGELOG.md
  thoth/workflow_helpers/__init__.py
Labels: approved, bot, size/XS

#149 Automatic update of dependency thoth-messaging from 0.7.11 to 0.7.13
  Pipfile.lock
Labels: approved, bot, size/L

#150 Add method to send unresolved packages message from adviser report inspection
  README.md
  app.sh
  parse_adviser_output.py
  qeb_thamos_advise.py
Labels: approved, size/L

#152 Release of version 0.1.18
  CHANGELOG.md
  thoth/workflow_helpers/__init__.py
Labels: approved, bot, size/XS

#153 lock down thoth-messaging
  Pipfile
  Pipfile.lock
Labels: approved, size/L

#155 Method should not fail and output default always present
  parse_adviser_output.py
Labels: approved, size/M

#156 Do not return before saving default
  parse_adviser_output.py
Labels: approved, size/M

#158 Release of version 0.1.19
  CHANGELOG.md
  thoth/workflow_helpers/__init__.py
Labels: approved, bot, size/XS

#159 Automatic update of dependency thoth-common from 0.20.1 to 0.20.2
  Pipfile.lock
Labels: approved, bot, size/M

#161 Automatic update of dependency thamos from 1.0.1 to 1.1.1
  Pipfile.lock
Labels: approved, bot, size/L

#162 Automatic update of dependency thoth-common from 0.20.2 to 0.20.4
  Pipfile.lock
Labels: approved, bot, size/L

#164 Automatic update of dependency thoth-storages from 0.25.15 to 0.25.16
  Pipfile.lock
Labels: approved, bot, size/L
