Repository thoth-station/workflow-helpers, pull requests merged in 2020-08, with the labels that each got.

#35 Release of version 0.1.2
  CHANGELOG.md
  thoth/workflow_helpers/__init__.py
Labels: approved, bot, size/XS

#36 Use custom name for file
  parse_solver_inputs.py
Labels: approved, size/XS

#38 Automatic update of dependency thamos from 0.10.6 to 0.11.0
  Pipfile.lock
Labels: approved, bot, size/M

#39 Automatic update of dependency thamos from 0.10.6 to 0.11.0
  Pipfile.lock
Labels: approved, bot, size/M

#40 Automatic update of dependency thoth-python from 0.10.0 to 0.10.1
  Pipfile.lock
Labels: approved, bot, size/M

#42 Release of version 0.1.3
  CHANGELOG.md
  thoth/workflow_helpers/__init__.py
Labels: approved, bot, size/XS

#43 include aicoe-ci configuration file
  .aicoe-ci.yaml
  .zuul.yaml
Labels: approved, size/M

#47 Automatic update of dependency thamos from 0.11.0 to 0.11.1
  Pipfile.lock
Labels: approved, bot, size/S

#44 Add parse solved method
  Pipfile
  Pipfile.lock
  parse_solved_package.py
  parse_solver_inputs.py
Labels: approved, size/L

#46 Consider multiple indexes
  parse_solver_inputs.py
Labels: approved, size/M

#49 Add pre-commit and correct errors
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
  .github/PULL_REQUEST_TEMPLATE.md
  .pre-commit-config.yaml
  MANIFEST.in
  README.md
  parse_solved_package.py
  parse_solver_inputs.py
  qeb_thamos_advise.py
  select_thoth_integration.py
  thoth/workflow_helpers/trigger_finished_webhook.py
Labels: approved, size/L

#50 Update files
  README.md
  app.sh
Labels: approved, size/M
