Repository thoth-station/workflow-helpers, pull requests merged in 2020-07, with the labels that each got.

#22 Automatic update of dependency thamos from 0.10.5 to 0.10.6
  Pipfile.lock
Labels: approved, bot, size/M

#23 Automatic update of dependency thoth-common from 0.13.13 to 0.14.2
  Pipfile.lock
Labels: approved, bot

#20 More robust app.sh
  app.sh
Labels: approved, size/S

#26 fixes issue 21
  app.sh
  download_py_package.py
Labels: approved, size/XS

#25 Add method to produce inputs for Kafka CLI
  app.sh
  download_py_package.py
  parse_solver_inputs.py
  thoth/workflow_helpers/trigger_finished_webhook.py
Labels: approved, size/M

#30 Release of version 0.1.1
  CHANGELOG.md
  thoth/workflow_helpers/__init__.py
Labels: approved, bot, size/S

#31 parse git service and remove f.close(context managers)
  select_thoth_integration.py
Labels: approved, size/XS

#32 Automatic update of dependency thoth-common from 0.14.2 to 0.16.0
  Pipfile.lock
Labels: approved, bot, size/M
