Repository thoth-station/workflow-helpers, pull requests merged in 2020-09, with the labels that each got.

#52 Add message content for service name and version sending Kafka Messages
  parse_solved_package.py
  parse_solver_inputs.py
  thoth/workflow_helpers/common.py
Labels: approved, size/M

#54 Automatic update of dependency thamos from 0.11.1 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/M

#55 Automatic update of dependency thamos from 0.11.1 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/M

#56 Automatic update of dependency thoth-common from 0.16.1 to 0.17.2
  Pipfile.lock
Labels: approved, bot, size/M

#57 Release of version 0.1.4
  CHANGELOG.md
  thoth/workflow_helpers/__init__.py
Labels: approved, bot, size/S

#59 Automatic update of dependency thamos from 0.12.0 to 0.12.2
  Pipfile.lock
Labels: approved, bot, size/L

#60 update base image to be used for build.
  .aicoe-ci.yaml
Labels: approved, size/XS

#62 Automatic update of dependency thoth-common from 0.17.2 to 0.17.3
  Pipfile.lock
Labels: approved, bot, size/XS

#63 Fix metadata missing in adviser workflow task to run trigger-finished-webhook
  thoth/workflow_helpers/trigger_finished_webhook.py
Labels: approved, size/S

#65 Release of version 0.1.5
  CHANGELOG.md
  thoth/workflow_helpers/__init__.py
Labels: approved, bot, size/S

#66 Automatic update of dependency thoth-storages from 0.25.5 to 0.25.6
  Pipfile.lock
Labels: approved, bot, size/S

#67 Change name because overwrite Argo default
  select_thoth_integration.py
Labels: approved, size/XS

#68 Automatic update of dependency thoth-common from 0.17.3 to 0.18.1
  Pipfile.lock
Labels: approved, bot

#69 Automatic update of dependency thoth-storages from 0.25.6 to 0.25.7
  Pipfile.lock
Labels: approved, bot, size/S

#72 Release of version 0.1.6
  CHANGELOG.md
  thoth/workflow_helpers/__init__.py
Labels: approved, bot, size/S

#73 Add info version when running any task from workflow-helpers
  download_py_package.py
  parse_solved_package.py
  parse_solver_inputs.py
  qeb_thamos_advise.py
  select_thoth_integration.py
Labels: approved, size/S

#75 Automatic update of dependency thoth-common from 0.18.1 to 0.18.2
  Pipfile.lock
Labels: approved, bot

#77 Release of version 0.1.7
  CHANGELOG.md
  thoth/workflow_helpers/__init__.py
Labels: approved, bot, size/XS

#78 Show all thoth libraries versions in logs
  parse_solved_package.py
  parse_solver_inputs.py
  thoth/workflow_helpers/__init__.py
Labels: approved, size/S

#79 Make pre-commit happy
  parse_solver_inputs.py
Labels: approved, size/XS

#80 Automatic update of dependency thoth-common from 0.18.2 to 0.18.3
  Pipfile.lock
Labels: approved, bot

#81 Automatic update of dependency thoth-storages from 0.25.7 to 0.25.8
  Pipfile.lock
Labels: approved, bot, size/S

#83 Use correct value
  parse_solved_package.py
Labels: approved, size/XS

#86 Release of version 0.1.8
  CHANGELOG.md
  thoth/workflow_helpers/__init__.py
Labels: approved, bot, size/S

#82 Store file always to avoid workflow failing
  parse_solved_package.py
  parse_solver_inputs.py
Labels: approved, size/S

#88 Automatic update of dependency thamos from 0.12.2 to 1.0.0
  Pipfile.lock
Labels: approved, bot, size/M

#89 Automatic update of dependency thoth-common from 0.18.3 to 0.19.0
  Pipfile.lock
Labels: approved, bot, size/M

#90 Release of version 0.1.9
  CHANGELOG.md
  thoth/workflow_helpers/__init__.py
Labels: approved, bot, size/XS

#94 Automatic update of dependency thoth-storages from 0.25.8 to 0.25.9
  Pipfile.lock
Labels: approved, bot

#95 Add more logs
  parse_solver_inputs.py
Labels: approved

#97 Release of version 0.1.10
  CHANGELOG.md
  thoth/workflow_helpers/__init__.py
Labels: approved, bot

#98 Show messages sent
  parse_solved_package.py
  parse_solver_inputs.py
Labels: approved, size/XS

#100 Automatic update of dependency thoth-storages from 0.25.9 to 0.25.10
  Pipfile.lock
Labels: approved, bot, size/M

#101 Automatic update of dependency thoth-storages from 0.25.9 to 0.25.10
  Pipfile.lock
Labels: approved, bot, size/M

#102 Release of version 0.1.11
  CHANGELOG.md
  thoth/workflow_helpers/__init__.py
Labels: approved, bot, size/XS

#103 Add missing '
  parse_solved_package.py
  parse_solver_inputs.py
Labels: approved, size/XS

#105 Release of version 0.1.12
  CHANGELOG.md
  thoth/workflow_helpers/__init__.py
Labels: approved, bot, size/XS

#110 store default empty string for other source types
  select_thoth_integration.py
Labels: approved, size/XS

#107 parse solver document
  app.sh
  parse_solved_package.py
  parse_solver_inputs.py
  parse_solver_output.py
  thoth/workflow_helpers/common.py
Labels: approved, size/L

#112 Automatic update of dependency thoth-common from 0.19.0 to 0.20.0
  Pipfile.lock
Labels: approved, bot, size/L

#115 Automatic update of dependency thoth-python from 0.10.1 to 0.10.2
  Pipfile.lock
Labels: approved, bot, size/L

#118 Automatic update of dependency thoth-storages from 0.25.10 to 0.25.11
  Pipfile.lock
Labels: approved, bot, size/L

#121 Release of version 0.1.13
  CHANGELOG.md
  thoth/workflow_helpers/__init__.py
Labels: approved, bot, size/S
