Repository thoth-station/workflow-helpers, pull requests merged in 2020-06, with the labels that each got.

#2 Introduce methods for workflow tasks
  .github/CODEOWNERS
  .zuul.yaml
  Pipfile
  Pipfile.lock
  README.md
  app.sh
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
  qeb_thamos_advise.py
  select_thoth_integration.py
  template/__init__.py
  thoth/workflow_helpers/__init__.py
  thoth/workflow_helpers/configuration.py
  thoth/workflow_helpers/exception.py
  thoth/workflow_helpers/trigger_finished_webhook.py
Labels: approved, size/XXL

#5 Remove import
  select_thoth_integration.py
Labels: approved, size/XS

#6 small bugs
  select_thoth_integration.py
Labels: approved, size/XS

#7 Improve readme
  README.md
Labels: size/S

#8 Add error type
  qeb_thamos_advise.py
  thoth/workflow_helpers/trigger_finished_webhook.py
Labels: approved, size/XS

#13 create workflow helper for downloading pypackage
  Pipfile
  Pipfile.lock
  app.sh
  download_py_package.py
  thoth/workflow_helpers/configuration.py
Labels: approved, size/L

#16 Automatic update of dependency thoth-python from 0.9.2 to 0.10.0
  Pipfile.lock
Labels: approved, bot, do-not-merge/needs-rebase, size/M

#15 Automatic update of dependency thoth-common from 0.13.8 to 0.13.12
  Pipfile.lock
Labels: approved, bot, size/M

#19 Automatic dependency re-locking
  Pipfile.lock
Labels: bot, size/L
