Repository thoth-station/workflow-helpers, pull requests merged in 2020-12, with the labels that each got.

#175 Add pre-commit and dev packages
  .pre-commit-config copy.yaml
  Pipfile
  Pipfile.lock
Labels: approved, size/L

#172 Update .thoth.yaml
  .thoth.yaml
Labels: size/XS

#167 get inspection info from env
  app.sh
  create_inspection_complete_message.py
Labels: approved, size/M
