Repository thoth-station/workflow-helpers, pull requests merged in 2021-08, with the labels that each got.

#304 Refactor methods for metrics and add new one for purge job
  create_purge_issues.py
  kebechet_administrator.py
  parse_adviser_output.py
  parse_provenance_checker_output.py
  parse_solver_output.py
  thoth/workflow_helpers/common.py
Labels: size/L, approved

#312 storages function uses wrong function name
  Pipfile.lock
  create_purge_issues.py
Labels: size/L, approved

#314 Fix env variable in kebechet administrator
  kebechet_administrator.py
Labels: approved, size/XS

#319 Fix kebechet administrator scheduling
  kebechet_administrator.py
Labels: approved, size/XS

#326 add list of available runtimes to purge issue
  create_purge_issues.py
Labels: size/S
