Repository thoth-station/workflow-helpers, pull requests merged in 2021-04, with the labels that each got.

#234 Adjust AdviserTrigger message inputs from qeb advise workflow helper task
  qeb_thamos_advise.py
Labels: approved, size/XS

#229 remove extra message contents removed in v2
  parse_solver_output.py
Labels: approved, size/S

#236 Messaging pydantic
  .pre-commit-config.yaml
  .prow.yaml
  Pipfile
  Pipfile.lock
  create_inspection_complete_message.py
  download_py_package.py
  kebechet_administrator.py
  mypy.ini
  parse_adviser_output.py
  parse_provenance_checker_output.py
  parse_solver_output.py
  qeb_thamos_advise.py
Labels: approved, size/L

#239 Use thamos and not messaging for qeb-hwt workflow
  .pre-commit-config copy.yaml
  Pipfile.lock
  qeb_thamos_advise.py
Labels: approved, size/L

#245 Adjust input to thamos method
  qeb_thamos_advise.py
Labels: approved, size/XS
