Repository thoth-station/workflow-helpers, pull requests merged in 2021-06, with the labels that each got.

#251 enable sending missing package messages
  kebechet_administrator.py
  thoth/workflow_helpers/configuration.py
Labels: approved, size/S

#270 mypy error fix for workflow-helpers
  .prow.yaml
  mypy.ini
Labels: size/XS

#275 Relock to fix missing typing_extensions
  Pipfile.lock
Labels: approved, size/M

#223 new workflow helpers task to update keb installation in DB
  Pipfile
  Pipfile.lock
  app.sh
  kebechet_administrator.py
  mypy.ini
  thoth/workflow_helpers/py.typed
  update_keb_installation.py
Labels: approved, kind/demo, kind/feature, lifecycle/active, priority/important-soon, sig/docs, size/L

#285 Deprecate qeb-hwt
  parse_solver_output.py
  qeb_thamos_advise.py
  select_thoth_integration.py
  thoth/workflow_helpers/configuration.py
  thoth/workflow_helpers/trigger_finished_webhook.py
Labels: approved, lgtm, size/L
