Repository thoth-station/workflow-helpers, pull requests merged in 2021-07, with the labels that each got.

#293 Clean methods and README
  README.md
  app.sh
Labels: lgtm, size/S

#292 Use common enums
  parse_solver_output.py
Labels: approved, size/XS

#296 add more args for issue/pr context and adviser update runs
  kebechet_administrator.py
Labels: approved, size/S

#301 add new script for opening issues on data purge
  app.sh
  create_purge_issues.py
  thoth/workflow_helpers/exception.py
Labels: approved, size/M

#302 Fix sending metric twice
  parse_solver_output.py
Labels: approved, size/XS
