Repository thoth-station/workflow-helpers, pull requests merged in 2021-01, with the labels that each got.

#187 Send also runtime environment in adviser trigger message
  qeb_thamos_advise.py
Labels: approved, size/S

#191 Change base image for build
  .aicoe-ci.yaml
Labels: approved, size/S

#192 Always store file to avoid error in Argo
  parse_adviser_output.py
  parse_solver_output.py
  qeb_thamos_advise.py
  thoth/workflow_helpers/common.py
Labels: approved, size/M

#195 update to latest messaging
  Pipfile
  Pipfile.lock
Labels: approved, size/XL

#198 change message contents of inspection complete
  .pre-commit-config.yaml
  create_inspection_complete_message.py
Labels: approved, size/S

#197 Introduce metrics for revision
  Pipfile
  Pipfile.lock
  graph_schema_update.py
  kebechet_administrator.py
  parse_adviser_output.py
  parse_solver_output.py
  qeb_thamos_advise.py
  thoth/workflow_helpers/common.py
  thoth/workflow_helpers/configuration.py
Labels: approved, size/M
